# Preface

Hints on Child-Training may be helpful, where a formal treatise on the subject would prove be- wildering. It is easier to see how one phase or another of children's needs is to be met, than it is to define the relation of that phase of the case to all other phases, or to a system that includes them all. Therefore it is that this series of Hints is ventured by me for the benefit of young parents, although I would not dare attempt a systematic treatise on the entire subject here touched upon.

Thirty years ago, when I was yet a young father, a friend, who knew that I had for years been in- terested in the study of methods of education, said to me, " Trumbull, what is your theory of child- training? " " Theory?" I responded. "I have no theory in that matter. I had lots of theories before I had any children; but now I do, with fear and trembling, in every case just that which seems to be the better thing for the hour, whether it agrees with any of my old theories or not."

Whatever theory of child-training may show itself in these Hints, has been arrived at by induc- tion in the process of my experiences with children since I had to deal with the matter practically, apart from any preconceived view of the principles involved. Every suggestion in these Hints is an outcome of experiment and observation in my life as a father and a grandfather, while it has been carefully considered in the light of the best lessons of practical educators on every side.

These Hints were begun for the purpose of giv- ing help to a friend. They were continued because of the evident popular interest in them. They are sent out in this completed form in the hope that they will prove of service to parents who are feel- ing the need of something more practical in the realm of child-training than untested theories.

H. Clay Trumbull. Philadelphia, September 15, 1890.