# Training A Child To Self-Control



An inevitable struggle between the individual and the several powers that go to make his individu- ality, begins in every child at his very birth, and continues so long as his life in the flesh continues. On the outcome of this struggle depends the ulti- mate character of him who struggles. It is, to him, bondage or mastery, defeat or triumph, failure or success, as a result of the battling that cannot be evaded. And, as a matter of fact, the issue of the life-long battle is ordinarily settled in child- hood.

A child who is trained to self-control — as a child

may be — is already a true man in his fitness for

manly self-mastery. A man who was not trained,

in childhood, to self-control, is hopelessly a child

93



94 HINTS ON CHILD-TRAINING.

in his combat with himself; and he can never regain the vantage-ground which his childhood gave to him, in the battle which then opened before him, and in the thick of which he still finds him- self It is in a child's earlier struggles with himself that help can easiest be given to him, and that it is of greatest value for his own developing of charac- ter. Yet at that time a child has no such sense of his need in this direction as is sure to be his in maturer years; hence it is that it rests with the parent to decide, while the child is still a child, whether the child shall be a slave to himself, or a master of himself; whether his life, so far, shall be worthy or unworthy of his high possibilities of manhood.

A child's first struggle with himself ought to be in the direction of controlling his impulse to give full play to his lungs and his muscles at the prompting of his nerves. As soon as the nerves make themselves felt, they prompt a child to cry, to thrash his arms, to kick, and to twist his body on every side, at the slightest provocation, — or at



HINTS ON CHILD-TRAINING. 95

none. Unless this prompting be checked, the child will exhaust himself in aimless exertion, and will increase his own discomfort by the very means of its exhibit. A control of himself at this point is possible to a child, at an age while he is yet unable to speak, or to understand what is spoken to him. If a parent realizes that the child must be induced to control himself, and seeks in loving firmness to cause the child to realize that same truth, the child will fed the parent's conviction, and will yield to it, even though he cannot compre- hend the meaning of his parent's words as words. The way of helping the child will be found, by the parent who wills to help him. To leave a child to himself in these earliest struggles with himself, is to put him at a sad disadvantage in all the future combats of his life's warfare; while to give him wise help in these earliest struggles, is to give him help for all the following struggles.

As soon as a child is able to understand what is said to him, he ought to be taught and trained to control his impulse to cry and writhe under the



96 HINTS ON CHILD-TRAINING.

pressure of physical pain. When a child has fallen and hurt himself, or has cut his finger, or has burned his hand, or has been hit by an ill-directed missile, it is natural for him to shriek with pain and fright, and it is natural for his tender-hearted mother to shrink from blaming him just then for indulging in this display of grief But ever at such a time as this, a mother has an unmistakable duty of helping her child to gain a measure of control over himself, so as to repress his cries and to mod- erate his exhibit of disturbed feeling.

A child can come to exercise self-control under such circumstances as these. His mother can enable him to do this. It is better for both child and mother that he should have her help accord- ingly. Because of the lack of help just here, many a child is a sufferer through life in his inabil- ity to control himself under physical pain. And because of this inability many a person has actually lost his life, at a time when calmness of mind was essential to that endurance of physical suffering which was the only hope of prolonged existence.



HINTS ON CHILD-TRAINING. 97

Because he was not trained to control his nerves, he is hopelessly controlled by his nerves.

Coaxing and rewarding a child into quiet at such a time is not what is needed; but it is the encour- aging a child into an intelligent control of himself, that is to be aimed at by the wise parent. It is only a choice between evils that substitutes a candy- paid silence for a noisy indulgence of feeling on a child's part. A good illustration of the unwise way of inducing children to seem to have control of themselves, is given in the familiar story of the little fellow throwing himself on the floor and kicking and yelling, and then crying out, " Grand- ma, grandma, I want to be pacified. Where are your sugar-plums?"

Dr. Bushnell, protesting against this method of coaxing a child out of a state of irritation, in a fit of ill-nature, by " dainties that please the taste," says forcefully, " It must be a very dull child that will not cry and fret a great deal, when it is so pleasantly rewarded. Trained, in this manner, to play ill-nature for sensation's sake, it will go on

7



98 HINTS ON CHILD-TRAINING.

rapidly, in the course of double attainment, and will be very soon perfected in the double character of an ill-natured, morbid sensualist, and a feigning cheat besides. By what methods, or means, can the great themes of God and religion get hold of a soul that has learned to be governed only by rewards of sensation, paid to affectations of grief and deliberate actings of ill-nature ?"

That control of himself which is secured by a child in his intelligent repression of an impulse to cry and writhe in physical pain, is of advantage to the child in all his life -long struggle with himself; and he should be trained in the habit of making his self-control available to him in this struggle. " I buffet my body [or give it a black eye] and bring it into bondage; lest by any means, after that I have preached to others, I myself should be rejected," says the Apostle Paul; as if in recogni- tion of the fact that a man's battle with his body is a vital conflict, all his life through. Every child needs the help of his parents in gaining control over his body, instead of allowing his body to gain



I



HINTS ON CHILD-TRAINING. 99

the control of him. The appetites and passions and impellings of the outer man are continually- striving for the mastery over the inner man; and unless one is trained to master these instead of being mastered by them, he is sure to fail in his life-struggle.

A parent ought to help his child to refrain from laughing when he ought not to laugh; from crying when he ought not to cry; from speaking when he ought not to speak ; from eating that which he ought not to eat, even though the food be imme- diately before him ; from running about when it is better for him to remain quiet ; and to be ready to say and to do just that which it is best for him to say and do, at the time when it needs to be said and done. Self-control in all these things is possi- ble to a child. Wise training on the parent's part can secure it. The principle which is operative here, is operative in every sphere of human exist- ence. By means of self-control a child is made happier, and is fitted for his duties, while a child and ever after, as otherwise he could not be. Many



JOO HINTS ON CHILD-TRAINING.

a man's life-course is saddened through his hopeless lack of that self-control to which he could easily have been helped in childhood, if only his parents had understood his needs and been faithful accord- ingly.