# Training A Child To Courtesy

Unless a man is courteous toward others, he is at a disadvantage in the world, even though he be the possessor of every other good trait and quality possible to humanity, and of every material, mental, and spiritual acquisition which can belong to mere man. And if a man be marked by exceptional courtesy in all his intercourse with others, he has an advantage to start with in the struggle of life, beyond all that could be his in health and wealth and wisdom without courtesy. Yet courtesy is never wholly a natural quality. It is always a result of training; albeit the training will be far easier in one case than in another.

Courtesy is the external manifestation of a right spirit toward others. Its basis is in an unselfish and a fitting regard for the rights and feelings of those with whom one is brought into intercourse; but the principles of its expression must be a matter of wise study on the part of those who have had experience in the ways of the world, and who would give the benefit of their experience to those who come after them. Courtesy is not merely a surface finish of manners; although courtesy is sure to show itself in a finished surface of manners. Good breeding, politeness, and fine manners, are all included in the term "courtesy;" but these all are the expression of courtesy, rather than its essence and inspiration. "Good breeding," says one, "is made up of a multitude of petty sacrifices." "True politeness," says another, "is the spirit of benevolence showing itself in a refined way. It is the expression of good-will and kindness." Fine manners, De Quincey says, consist "in two capital features: first of all, respect of others; secondly, in self-respect."

The courteous man is sure not to be lacking in self-respect, but he is sure to be lacking in self-assertion. His self-respect is shown in his sense of a responsibility for the comfort and welfare of others; and his unselfish interest in others causes him to lose all thought of himself in his effort to discharge his responsibility toward others. His courtesy will be evidenced in what he is ready to do for others, rather than in what he seems to look for from others.

Attractiveness of personal appearance, gracefulness in bearing, tastefulness in dress, elegance in manners, and carefulness in word and tone of voice, may, indeed, all be found where there is no true courtesy. The very purpose on the part of their possessor to be thought courteous, to command respect, and to appear to advantage, may cause him or her to show a lack of courtesy, to fail of commanding respect, and to appear far otherwise than advantageously. On the other hand, there are, for example, ladies whose attractions of face and form are but slight, who care little for dress, who pay no attention to mere manners, who are yet so unselfishly thoughtful of others, in all their intercourse with them, that they are called "just delightful" by everybody who knows them. When they have callers, or when they are making calls, they have absolutely no thought about themselves, their appearance, their modes of expression, or the impression they may make on others. They are for the time being absolutely given up to those with whom they converse. They question and listen with enthusiastic interest; they say kindly words because they feel kindly; they avoid unpleasant subjects of mention, and they introduce topics that cannot but be welcome. Because they keep self out of sight, they win respect, admiration, and affection, beyond all that they would dare hope for. And many a man shows a similar self-forgetfulness in his courteous interest in others, and wins a loving recognition of his courtesy on every side. Real courtesy is, however, impossible, in either sex, except where self is practically lost sight of.

In training a child to courtesy, it is of little use to tell him to be forgetful of himself; but it is of value to tell him to be thoughtful of others. The more a person tries to forget himself, the surer he will be to think of himself often, indeed, it is the very effort of a person to forget himself, that makes that person painfully self-conscious, and causes him to seem bashful and embarrassed. But when a child thinks of others, his thoughts go away from himself, and self-forgetfulness is a result, rather than a cause, of his action.

To tell a young person to enter a full room without any show of embarrassment, or thought of himself, is to put a barrier in the way of his being self-possessed through self-forgetfulness. But to send a young person into a full room with a life-and-death message to some one already there, is to cause him to forget himself through filling him with thought of another. And this distinction in methods of training is one to be borne in mind in all endeavors at training children to courtesy.

In order to be courteous, a child must have a care to give due deference to others, in his ordinary salutations and greetings, and in his expression of thanks for every kindness or attention shown to him. So far most parents, who give any thought to a matter like this, are ready to go. But true courtesy includes a great deal more than this; and a child needs training accordingly.

Many a boy who is careful to give a respectful greeting to his superiors on the street, or in the house, and who never fails to proffer thanks for any special favor shown to him, lacks greatly in courtesy in his ordinary intercourse with others, because he has not been trained to feel and to show an unselfish interest in those with whom he is brought face to face. Such a boy is more ready to talk of himself, and of that which has a personal interest to him, than to find out what has an interest to others, and to make himself interested in that, or to express his interest in it if he already feels such an interest. If, indeed, from any reason, he finds himself unable to talk freely of that which immediately concerns him, he is often at a loss for a topic of conversation, and is liable to show awkwardness and embarrassment in consequence. And so while courteous at points of conventional etiquette, a boy of this sort is constantly exhibiting his lack of courtesy.

This liability of a child must be borne in mind by his parents in his training, and it must be guarded against by wise counsel and by watchful inquiry on their part. When a child has a playmate with him in his home, he must be trained to make it his first business to find out what that playmate would enjoy, and to shape his own words and ways in conformity with that standard, for the time being. When a child is going into another home, he must be told in advance of his duty to be a sharer with those whom he meets there, in their employments and pleasures, and to express heartily his sense of enjoyment in that which pleases them. When he returns from a visit from another home, he should be asked to tell what he found of interest there, and what he said about it while there; and he should be commended or counseled in proportion to his well-doing or his lack in his exhibit of courtesy in this connection. When he has been talking with an older person, in his own home or abroad, his parents ought to ascertain just how far he has been lacking in courtesy by putting himself forward unduly, or how far he has shown courtesy by having and evidencing an interest in that which was said to him or done for him by his superior; and kindly comment on his course should be given to him by his parents at such a time.

If, indeed, a child has shown any lack of courtesy toward another, whether a person of his own age or older, he should be instructed to be frank and outspoken in expression of his regret for his course, and of his desire to be forgiven for his fault. True courtesy involves a readiness to apologize for any and every failure, whether intentional or unintentional, to do or say just that which ought to have been done or said; and the habit of frank apologizing is acquired by a child only through his careful training in that direction. He who has any reluctance to proffer apologies on even the slightest cause for them, is sadly lacking in the spirit of courtesy; for just so far as one is thoughtfully considerate of the feelings of another will he want to express his regret that any performance or failure on his part has been a cause of discomfort to another.

All this is, of course, a trying matter to a child, and a taxing matter to a parent; but it is to the obvious advantage of both parties. If a child is seen to be lacking in courtesy, his parents are understood to be at fault in his training, so far. If, on the other hand, a child is not trained to courtesy while a child, he is at a disadvantage from his lack of training, as long as he lives. If he has not been trained to give others the first place in his thoughts, while he is with them, and to give open expression to all the interest in them which he really has, he cannot be free and unembarrassed in conversation with any and all whom he meets. If, on the other hand, he has had wise and careful training in this direction, he is sure to be as pleasing as he is courteous to others; and to receive as much enjoyment as he gives, through his courtesy in intercourse with all whom he meets.

Personal embarrassment in the presence of others, and a lack of freedom in the expression of one's interest in others, are generally the result of an undue absorption in one's own interests or appearance, and of one's lack of self-forgetful interest in the words and ways and needs of those whom he is summoned to meet. The surest protection of one's children against these misfortunes, is by the wise training of those children to have an interest in others, and to give expression to that interest, whenever they are with others, at home or abroad; and so to be courteous and to show their courtesy as a result of such training.