# The Value Of Table-Talk



In proportion as man rises in the intellectual scale, does he give prominence to mental and moral enjoyments in conjunction with his daily meals. He who looks upon the table merely as a place for feeding the body, is so far upon the level of the lower order of animals. He who would improve his time there for the advantage of his mind and character, as well as for the supply of his physical wants, recognizes a standard of utility in the hum- bler offices of daily life that is perceptible only to one whose higher nature is always striving for supremacy above the lower.

With all the tendency to excesses in the line of appetite among the Greeks and Romans in classic times, there were even then gleams of a higher

enjoyment at the table through social intercourse

187



1 88 HINTS ON CHILD -TRAINING.

than that which mere eating and drinking supplied. When the Perfect Man was here among men, he showed the possibiHty of making the household meal a means of mental and spiritual improving; and there are no profounder or more precious truths in the record of our Lord's earthly teach- ings, than those which are found in his words spoken to those who sat with him eating and drinking at their common meal. The "table talk" of great men has, for centuries, been recognized as having a freeness, a simplicity, and a forcefulness, not to be found in their words spoken elsewhere.

There are obvious reasons why the social talk at daily meals should possess a value not attain- able under other circumstances, in the ordinary Christian household. Just there is the place where all the members of the family must be together. However closely and however diversely they may be occupied at other times, when the hour for the household meal has arrived, everything else must be dropped by them all for the one duty of eating and drinking; and they must all come together



HINTS ON CHILD-TRAINING, 1 89

for that common purpose. In the very nature of things, too, those who have gathered at the family table must, for the time being, have left all their work behind them, and be in a state of relaxation and of kindlier feeling accordingly. Now it is, therefore, that they are freest to speak with one another of matters having a common interest to all, rather than to dwell in absorbed thought on the special duties from which they have, severally, turned away, or toward which they must turn at the meal's close.

It is a matter of fact that those who sit together at a family table, whether as members of the house- hold or as guests there for a season, learn to under- stand one another, and to give and receive help and inspiration in their social converse, as they could not without the advantage of this distinctive op- portunity. It is also a fact that only now and then is there a family circle the members of which rec- ognize at the fullest, and make available at the best, the value of table-talk as a training agency for all who have a share in it, or who are under its immediate influence. Yet he who w^ould train his



I go HINTS ON CHILD-TRAINING.

children as they should be trained, cannot ignore this important training agency without serious and permanent loss to them.

With family customs as they are in the United States, there is more of an opportunity here than abroad, for the training of children by means of table-talk. In England, and in Europe generally, young children are likely to be by themselves with nurses or governesses, at meal-time, rather than at the table with their parents. But in this country children are, as a rule, brought to the family table at a very early age, and are permitted to be there not merely while the members of the family are there gathered, but on occasions when a guest is, for the time being;, made a member of the house- hold circle. Therefore it is that an important fea- ture of child-training in American families is the table-talk in those families. This feature varies much in different homes; but at its best it is one of the most potent factors in the intellectual and moral training of the young.

Fifty years ago a gentleman of New England



HINTS ON CHILD-TRAINING. I9I

had, as a philanthropist, an educator, and an author, an exceptional acquaintance with men of prominence in similar fields of endeavor in this country and abroad. His home was a place of resort for them. He had a large family of chil- dren, all of whom were permitted to be at the family table while those guests were present, as well as at other times. The table-talk in that home, between the parents and the guests, or between the parents and their children when no guests were present, was in itself "a liberal education." It gave to those children a general knowledge such as they could hardly have obtained otherwise. It was a source of promptings and of inspiration to them in a multitude of directions. Now that they are themselves parents and grandparents, they perceive how greatly they were the gainers by their training through the table-talk of their early home; and they are doing what they can to have the value of table-talk as a training agency for the young recognized and made effective in the homes which they direct or influence.



1 92 HINTS ON CHILD - TRA INING.

In another New England home, the father was a man of quiet thoughtfulness, and at ordinary- times a man of peculiar reticence before his chil- dren. But at the family table he was accustomed to unbend as nowhere else. He, also, had a large family of children, and there were frequent visitors among them. The utmost freedom of question and of expression was cultivated in the table-talk of that home. The spirited discussions carried on there, between father and mother and children and visitors, were instructive, suggestive, and stimulat- ing, in a very high degree. The family table was, in fact, the intellectual and moral center of that home. No other place was so attractive as that. Not a person, young or old, would leave that table until he had to; and now that the survivors of that happy circle are scattered widely, every one of them will say that no training agency did more for him in his early life than the table-talk of his childhood's home.

In one home, where parents and children enjoy themselves in familiar and profitable table-talk, it



HINTS ON CHILD - TEA INING, 1 93

is a custom to settle on the spot every question that may be incidentally raised as to the pro- nunciation or meaning of a word, the date of a personage in ancient or modern history, the loca- tion of a geographical site, or anything else of that nature that comes into discussion at the family table. As an aid to knowledge in these lines, there stands in a corner of the dining-room a book-rest, on the top of which lies an English dictionary, while on the shelves below are a bio- graphical dictionary and a pronouncing gazeteer of the world, ready for instant reference in every case of dispute or doubt.

At the breakfast-table, in that home, the father runs his eye over the morning paper, and gives to his family the main points of its news which he deems worthy of special note in the family circle. The children there are free to tell of what they have studied in school, or to ask about points that have been raised by their teachers or companions. And in such ways the children are trained to an intelligent interest in a variety and range of sub-



194 HINTS ON CHILD-TRAINING.

jects that would otherwise be quite beyond their ordinary obsei"vation.

One father has been accustomed to treasure up the best things of his experience or studies for each day, with a view to bringing them attractively to the attention of his children at the family table, at the day's close, or at the next day's beginning. Another has had the habit of selecting a special topic for conversation at the dinner-table a day in advance, in order that the children may prepare themselves, by thinking or reading, for a share in the conversation. Thus an item in the morning paper may suggest an inquiry about Bismarck, or Gladstone, or Parnell, or Henry M. Stanley; and the father will say, " Now let us have that man be- fore us for our talk to-morrow at dinner. Find out all you can about him, and we will help one another to a fuller knowledge of him." In this way the children are being trained to an ever- broadening interest in men and things in the world's affairs, and to methods of thought and study in their search for knowledge.



HINTS ON CHILD-TRAINING, I95

There is no end to the modes of conducting table-talk as a means of child-training; and there is no end to the influence of table-talk in this direction, however conducted. Indeed, it may be said with truth, that table-talk is quite as likely to be influential as a means of child-traininp; when the parents have no thought of using it to this end, as when they seek to use it accordingly. At every family table there is sure to be talking; and the talk that is heard at the family table is sure to have its part in a child's training, whether the parents wish it to be so or not.

There are fathers whose table-talk is chiefly in complaint of the family cooking, or in criticism of the mother's method of managing the household. There are mothers who are more given to asking where on earth their children learned to talk and act as they do, than to inquiring in what part of the earth the m.ost important archaeological dis- coveries are just now in progress. And there are still more fathers and mothers whose table-talk is wholly between themselves, except as they turn



196 HINTS ON CHILD -TRAINING.

aside, occasionally, to say sharply to their little ones, "Why don't you keep still, children, while your father and mother are talking?" All this table-talk has its influence on the children. It leads them to have less respect for their parents, and less interest in the home table except as a place of satisfying their natural hunger. It is potent, even though it be not profitable.

Table-talk ought to be such, in every family, as to make the hour of home meal-time one of the most attractive as well as one of the most bene- ficial hours of the day to all the children. But in order to make table-talk valuable, parents must have something to talk about at the table, must be willing to talk about it there, and must have the children lovingly in mind as they do their table-talking.