# Guiding A Child In Companionships



A child cannot easily go on through childhood without companions, even if it were desirable for him to do so. Moreover, it is not desirable for a child to go on through childhood without compan- ions, even if it were every way practicable for him to do so. Companions are a necessity to a child, whether the case be looked at in the light of the world as it is, or in the light of the world as it ought to be. Hence, as a child will have compan- ions, and as he needs to have them, it is doubly im- portant that a parent be alive to the importance of guiding his every child in the choice of his com- panions and in his relations to those companions whom he has without choosing.

No child can be rightly trained all by himself,

197



198 HINTS ON CHILD-TRAINING.

nor yet wholly by means of those agencies and influences that come to him directly from above his head. There are forces which operate for a child's training through being brought to bear upon him laterally rather than perpendicularly; coming in upon him by way of his sympathies, in- stead of by way of his natural desire for knowl- edge. There are lessons which a child cannot learn so well from an elder teacher above him as from a young teacher alongside of him. There are impulses which can never be at their fullest with a child when he is alone as a child, but which will fill and sway him when they are operative upon him as one of a little company of children. Only as he learns these lessons from, and receives these impulses with, wisely chosen and fitting com- panions, can a child have the benefit of them to which he is fairly entitled.

Any observing parent will testify that, on more than one occasion, his child has come to him with a new interest in a thought or a theme, inspired by the words or example of a young companion, to



HINTS ON CHILD - TEA INING. 1 99

the surprise of the parent — who had before sought in vain to excite an interest in that very direction. All that the parent had said on the subject had been of no value, in comparison with that which had been said or done by the child's companion, as another self Again, there are few parents who have not found to their regret that their child has received lessons and impulses directly opposed to all the parental counsel and purposes, through a brief and comparatively unnoticed companionship that ought to have been guarded against. And these are but illustrations of the instructive and swaying power of child companionships. Such a power as this ought not to be ignored or slighted by any parent who would do most and best for his child's wise training.

Any thoughtful parent will realize that a child cannot be trained to be unselfishly considerate of his companions; to bear and forbear with compan- ions who are weak or impatient or exacting; to show sympathy with companions who need sym- pathy, and to minister lovingly to companions who



200 HINTS ON CHILD -TRAINING.

deserve a loving ministry, — unless he has compan- ions toward whom he can thus exercise and evi- dence a right spirit at all times. And no parent will say, or think, that it would be well for a child to be without these elements of character-training in his . life-progress.

An only child is naturally at a disadvantage in his home, because he is an only child. He lacks the lessons which playmates there would give him; the impulses and inspirations which he would re- ceive from their fellowship; the demands on his better nature, and the calls on his self-control and self-denial, which would come from their require- ments. Parents who have but one child ought to see to it that the lack in this regard is, in a measure, supplied by the companionships of children from other homes. It Is, Indeed, a mistake for any parent to attempt the training of his child with- out the help of child companionships. No child can be so inspiringly and symmetrically trained without, as with, these. Even where there are half a dozen or more children in one family, there



HINTS ON CHILD-TRAINING. 20I

is still a need of outside companions for each child, of the same age and wants of that child ; for it is not possible for any person to bring himself into the same relations with a child as can be entered into by a child of his own years and requirements.

Because a child's companionships are so influen- tial, it is the more important that they be closely watched and carefully guided by the child's parents. In choosing a neighborhood — for a residence or for a summer vacation ; in choosing a week-day school ; in choosing a Sunday-school, where a choice is open to the parents, the companionships thus secured to their child ought to have promi- nence in the minds of the parents. And when the neighborhood, and week-day school, and Sunday- school, are finally fixed upon, the responsibility is still upon the parent to see to it that the best avail- able companionships there are cultivated, and the most undesirable ones are shunned, by the child. Neglect or carelessness at this point may be a means of harm to the child for his lifetime. Atten-



202 HINTS ON CHILD -TRAINING.

tion just here may do more for him than were pos- sible through any other agency.

It is a parent's duty to know who are his child's companions, and to know the character, and course of conduct, and influence upon his child, of every one of those companions separately. Here is where a parent's chief work is called for in the matter of guiding and controlling his child's com- panionships. A parent must have his child's sym- pathy, in order to gain this knowledge; and a parent must give his sympathy to his child, in order to be able to use this knowledge wisely. It may be necessary to keep an open house for these companions, and an open heart and hand to them personally, as it surely is neces- sary to keep an open ear to the child's confi- dences concerning their sayings and doings, if the parent would know all about them that he needs to know. There are parents who do all this for and with their children, as an effective mealis of guiding those children in their companionships. It is a pity that there are not more who are willing to do



HINTS ON CHILD - TRA INING. 203

it, in view of all that it may be a means of accom- plishing for children.

Knowing his child's companionships, a parent ought to encourage such of them as are w^orthiest, and discourage such as he cannot approve. He ought to help his child to see the advantages of the one class and the disadvantages of the other, and to regulate his social intimacies according to the standards thus set before him. It will not do for a parent to allow matters in this line to take their own course, and to accept all companionships for his child just as they may come to him. He must feel responsible for his child's wise selection, from among the number of proffered companions, of those who are to be retained while others are dropped or avoided. And it devolves upon a parent to see to it that his child's companionships are of growing value to his companions as well as to himself; that his child's influence over his very playfellows is for their good, while his good is pro- moted by their association with him. A child's companionships, like those of older persons, ought



204 HINTS ON CHILD-TRAINING.

to be of advantage to both parties alike, through the very purpose of making them so.

Recognizing the desirableness and importance of companionships for his child, securing the best that are available, learning fully their characteristics and tendencies, aiding in their sifting, and seeking in their steady uplifting, a parent can do effective service in the way of guiding his child in and through that child's companionships. To neglect this agency of a child's training, would be to en- danger his entire career in life, whatever else were done in his behalf.