# Never Punish A Child In Anger



Anger is not always wrong. A parent may be angry without sin. And, as a matter of fact, most parents do get angry, whether they ought to or not. Children are sometimes very provoking, and parents are sometimes very much provoked. It is not always wrong to punish a child. A child may need punishing, and it may be a parent's duty to punish a child accordingly. But it is always wrong for a parent to punish a child in anger; and how- ever great may be the need of a child's punishing, a parent ought never to administer punishment to a child while angry.

Here is a rule which, strictly speaking, knows

no exception; yet, as a matter of fact, probably

nine-tenths of all the punishing of children that is

done by parents in this world is done in anger.

205



206 HINTS ON CHILD-TRAINING.

And this is one of the wrongs suffered by children through the wrong-doing of their parents.

Anger is hot blood. Anger is passion. Anger is for the time being a controlling emotion, fixing the mind's eye on the one point against which it is specifically directed, to the forgetfulness of all else. But punishment is a judicial act, calling for a clear mind, and a cool head, and a fair considering of every side of the case in hand. Anger is incon- sistent with the exercise of the judicial faculty; therefore no person is competent to judge fairly wdiile angry.

If, indeed, in any given case, the anger itself be just, the impulse of the angry man may be in the right direction, and the punishment he would in- flict a fitting one ; but, again, his impulse may be toward a punishment that is not merited. At all events, the man is not in a frame of mind to decide whether or not his impulse is a wise one; and it is his duty to wait until he can dispassionately view the case in another light than that in which it pre- sents itself to his heated brain. No judge is



worthy of the office he administers, if he acts on the impulse of his first estimate of a case before him, without taking time to see what can be shown on the other side of that case. And no parent acts worthily who jumps to the punishment of a child while under the impulse of an angry mood.

There are strong provocatives to anger in many a child's conduct, especially to a parent who is of an intense nature, with an inclination to quickness of temper. A child is disobedient at a point where he has been repeatedly told of his duty; he is quarrelsome with his playmates, or insolent toward his nurse ; he is persistently irritable, or he gives way to a fit of ungovernable rage; he destroys property recklessly, or he endangers life and limb; he snatches away a plaything from a little brother, or he clutches his hands into his mother's hair; he indulges in foul language, or he utters threats of revenge; he meets a proffered kiss with a slap or a scratch; his conduct may be even that which would excite anger in a saint, but it certainly is such as to excite anger in the average parent — who



208 HINTS ON CHILD-TRAINING,

is not a saint. Then, while the parent is angry, and while punishment seems merited by the child, the temptation of the parent is to administer punish- ment ; but that temptation is one that ought never to be yielded to, or, if yielded to, it is not with- out sin.

Punishment may be needed in such a case, but the punishment, to be surely just and to be rec- ognized as just, must be well considered, and must be administered in a manner to show that it is not the outcome of passionate impulse. No punishment ought to be administered by a parent at any time that would not be administered by that parent when he was cool and calm and deliberate, and after he had had a full and free talk on the sub- ject with the child, in the child's best state of mind. Whether the punishment that seems to the parent to be the desert of the child, while the parent is still angry, is the punishment that the parent would deem the fitting one in his cooler, calmer moments, can be better decided after the parent has looked at it in both frames of mind, than before he has



HINTS ON CHILD-TRAINING. 209

had the advantage of a view from the standpoint of fuller deliberation.

"What?" inquired a surprised parent, in con- versing with the present writer on this very sub- ject, " do you say that I must never punish my boy while I'm angry with him ? Why then I should hardly ever punish him at all. It is while I am sitting up for him hour after hour, when I've told him over and over again that he must come in early, evenings, that I feel like taking hold of him smartly when he does come in. If I should say nothing to him then, but should leave the matter until the next morning, I should sleep off all my feeling on the subject, and he wouldn't be punished at all." And that father, in that statement of the case, spoke for many a parent, in the whole matter of the punishing of a child while angry. The pun- ishment which the child gets is the result of the passion of the parent, not of the parent's sense of justice; and the child knows this to be the case, whether the parent does or not.

How many boxes of the ear, and shakings of the 14



2 1 HINTS ON CHILD - TEA INING,

shoulders, and slappings and strikings, and sen- tences of doom, which the children now get from their parents, would never be given if only the parents refrained from giving these while angry, but waited until they themselves were calm and unruffled, before deciding whether to give them or not! It is not by any means easy for a parent always to control himself in his anger, so as to refrain from acting on the impulse which his anger imparts ; but he who has not control of himself is the last person in the world to attempt the control of others. And not until a parent has himself in perfect control ought he to take his child in hand for the judicial investigation and treatment of his case as an evil-doer.

Of course, there are cases where instant action on the part of parents in checking or controlling their children's conduct is a necessity, whether the parent be excited or calm ; but in such cases the action, however vigorous or severe, is not in the line of punishment, but of conservation. A child may be thoughtlessly tugging away at the end of



HINTS ON CHILD-TRAINING. 211

a table-cloth, with the liability of pulling over upon his head all the table crockery, including the scald- ing teapot; or he may be endangering himself by reaching out toward a lighted lamp, or an open razor. No time is to be lost. If the child does not respond to a word, he must be dealt with promptly and decisively. A sharp rap on the fingers may be the surest available means of sav- ing him from a disaster.

So, again, a wayward child may be aiming a missile at a costly mirror, or at a playmate's head, in a fit of temper. Not a moment can then be wasted. Angry or not angry, the parent may have to clutch at the child's lifted arm to save property or life. In such a case, wise action is called for, regardless of the frame of mind of him who acts. But this is the action of the peacekeeper rather than of the minister of justice. The parent fills for the moment the place of the policeman on his beat, rather than of the judge on his bench. The question of punishment for the child's action is yet to be considered ; and that, again, must be



212 HINTS ON CHILD-TRAINING,

delayed until there is no anger in the parent's mind.

Anger, in the sense of hot indignation, may, in- deed, as has already been said, be, upon an occa- sion, a fitting exhibit of parental feeling ; but this is only in those utterly exceptional cases in which a child transcends all ordinary limits of misdoing, and is guilty of that which he himself knows to be intolerable. As Dr. Bushnell says at this point, " There are cases, now and then, in the outrageous and shocking misconduct of some boy, where an explosion is wanted; where the father represents God best by some terrible outburst of indignant violated feeling, and becomes an instant avenger, without any counsel or preparation whatever." But this is apart from all questions of punishment as punishment.

A child knows when punishment is adminis- tered to him in anger, and when it is administered to him in a purely judicial frame of mind; and a child puts his estimate accordingly on him who administers the punishment. In a city mission-



HINTS ON CHILD - TRA INING. 2 1 3

school, many years ago, there was a wild set of boys who seemed to do all in their power to anger and annoy their teachers. Cases of discipline were a necessity there; for again and again a boy at- tempted violence to a teacher, and force was required to save the teachers from serious harm. But love swayed those teachers even when force on their part was a necessity; and the boys seemed to understand this fully.

There came a time, however, when the young superintendent of that school, who had often held a scholar in check by force, was made public sport of in such way, with the rude linking of a lady teacher's name with his in ridicule, that his self- control failed him for the moment, and he evi- dently showed this as he took hold of the offender with unwonted warmth. Instantly the boy started back in surprise, with the reproachful exclama- tion: "Trumbull, you're mad; and that's wicked." Those words taught a lesson to that young super- intendent which he has never forgotten. They showed him that his power over those rough boys



214 HINTS OA CHILD -TRAINING.

was a moral power, and that it pivoted on his retaining power over himself. It was theirs to get him angry if they could; but if they succeeded he was a failure, and they knew it. And that les- son is one that parents as well as superintendents could learn to advantage.

When a parent punishes a child only in love, and without being ruffled by anger, the child is readier to perceive the justice of the punishment, and is junder no temptation to resent passion with passion. A child who had been told by her father, that if she did a certain thing he must punish her for it, came to him, on his return home, and informed him that she had transgressed in the thing for- bidden. He expressed sincere regret for this. " But you said, papa, that you would punish me for it," she added. "Yes, my dear child, and I must keep my word," was his answer. Then, as he drew her lovingly to him, he told her just why he must punish her. Looking up into his face with tearful trust, she said : " You don't like to punish me, — do you, papa?" " Indeed I don't, my



HINTS ON CHILD - TRA INING. 2 1 5

darling," he said, in earnestness. " It hurts you more than it hurts me, — doesn't it, papa ? " was her sympathetic question, as if she were more troubled for her father than for herself " Yes, indeed it does, my darling child," was his loving rejoinder. And the punishment which that father gave and that daughter received under circumstances like these, was a cause of no chafing between the two even for the moment, while it broucrht its craln to both, as no act of punishment in anger, however just in itself, could ever bring, in such a case.

As a rule, a child ought not to be punished except for an offense that, at the time of its com- mittal, was known by the child to be an offense deserving of punishment. It is no more fair for a parent to impose a penalty to an offense after the offense is committed, than it is for a civil govern- ment to pass an ex post facto law, by which punish- ment is to be awarded for offenses committed before that law was passed. And if a child understands, when he does a wrong, that he must expect a fixed punishment as its penalty, there is little danger of



2l6 HINTS ON CHILD-TRAINING.

his feeling that his parent is unjust in administer- ing that punishment; and, certainly, there is no need of the parent hastening to administer that punishment while still angry.

Punishment received by a child from an angry parent is an injury to both parent and child. The parent is the worse for yielding to the temptation to give way to anger against a child. The child is harmed by knowing that his parent has done wrong. A child can be taught to know that he deserves punishment. A child needs no teaching to know that his parent is wrong in punishing him while angry. No parent ought to punish a child except with a view to the child's good. And in order to do good to a child through his punishing, a parent must religiously refrain from punishing him while angiy.