# 26. Influence Of The Home Atmosphere



In 'the world of nature, life is dependent on the atmosphere. Whatever else is secured, the atmos- phere is essential to life's existence. It is, in fact, the atmosphere that gives the possibility of all the varied forms of vegetable and animal life in the earth and the sea and the air. So, again, the at- mosphere brings death to every living thing, if elements that are hostile to life prevail in its com- position. When the question of the date of man's first appearance on our planet is under discussion, a chief factor in the unsolved problem is the nature of the atmosphere of the earth at any given period of antiquity. Without a life-sustaining atmosphere, life were an impossibility. Similarly, the question

of the probability of other planets being inhabited,

17 257



258 HINTS ON CHILD-TRAINING.



pivots on this consideration. Life and death are in the atmosphere.

It is not alone the component elements of the atmosphere that bring life or death to all within its scope; but the temperature and the measure of movement of the atmosphere go far to decide the degree of life that shall be attained or preserved within the scope of its influence. Unless there is a due measure of oxygen in the air, the atmosphere is death-giving. Without sufficient warmth to the air, its oxygen is of no avail for the sustaining of life. And even though the oxygen and the warmth be present, the force of the swift-moving air may carry death on its vigorous wings. No gardener would depreciate the importance of a right atmos- phere for his most highly prized plants; nor would any wise physician undervalue the sanitary impor- tance of the atmospheric surroundings of his pa- tients. As it is in the natural world, so it is in the moral sphere : life and death are in the atmosphere,

A vital question in connection with every home is, Is the atmosphere of this home suited to the



HINTS ON CHILD-TRAINING. 2 $9

life and growth, to the developing of the vigor and beauty, of a child's best nature ? That question cannot always be answered in the affirmative ; and where it cannot be, it is of little use to talk of the minor training agencies which are operative in be- half of the children in that home.

The atmosphere of a home is the spirit of that home, as evidenced in the conduct and bearing of the parents, and of all whom the parents influence. The atmosphere itself — there, as in all the natural world — is not seen, but is felt. Its effects are clearly observable ; but as a cause it is inferred rather than disclosed. Indeed, the better the at- mosphere in a home, the more quietly pervasive its influence. Only as the home atmosphere is inimi- cal to the best interests of those who feel its power, does that atmosphere make itself manifest as an atmosphere, rather than give proof of its existence in results that cannot otherwise be ac- counted for.

You enter one home, and, mingling with the family there, you feel the balmy air of love and



26o HINTS ON CHILD-TRAINING,

sympathy. Parents and children seem to live for one another, and to be in complete accord in all their enjoyments and occupations ; and all is rest- ful in the peace that abides there. You are sure that everything in the moral and social atmosphere of that home tends to the fostering and growth of whatever is best in the child-nature. It is obvious that it is easier for a child to be good, and to do well, in such a home as that, than in. many another home.

You enter another home, and the chill of the household air strikes you unpleasantly, at the first greeting given to you by any member of the family. There is a side of the child-nature that you know needs more warmth than that for its developing. ■Again it is the burning heat of an excited and ever-driving household life that you are confident is withering the more delicate and sensitive tendrils of the young hearts being trained there. Yet again, it is the explosive storm-bursts of passion which tear through, the air, that make a home a place of peril to the young for the time being,



HINTS ON CHILD-TRAINING, 261

however it may seem in the lulls between tem- pests. In the one case as in the others, it is the home atmosphere that settles the question of the final tendency of the home training.

In view of the importance of the home atmos- phere, parents ought to recognize their responsi- bility for the atmosphere of the home they make and control. It is not enough for parents to have a lofty ideal for their children, and to instruct and train those children in the direction of that ideal. They must see to it that the atmosphere of their home is such as to foster and develop in their chil- dren those traits of character which their loftiest ideal embodies. That atmosphere must be full of the pure oxygen of love to God and love to man. It must be neither too hot in its intensity of social activities, nor too cold in its expressions of family affection, but balmy and refreshing in its uniform temperature of household living and being. It must be gentle and peaceful in its manner and movement of sympathetic intercourse. All this it may be. All this it ought to be.



262 HINTS ON CHILD-TRAINING,

Every home has its atmosphere, good or bad, health-promoting or disease-breeding. And parents are, in every case, directly responsible for the na- ture of the atmosphere in their home ; whether they have acted in recognition of this fact, or have gone on without a thought of it. In order to secure a right home atmosphere for their children, par- ents must themselves be right. They must guard against poisoning the air of the home with unlov- ing words or thoughts; against chilling it with unsympathetic manners, or overheating it with ex- citing ways ; against disturbing its peaceful flow with restlessness, with fault-findings, or with bursts of temper.

Parents must, as it were, keep their eyes on the barometer and the thermometer of the social life of the home, and see to it that its temperature is safely moderated, and that it is guarded against the effect of sudden storms. Only as such care is taken by wise parents, can the atmosphere in their home be what the needs of their children require it to be.